### ISSUE TITLE
Create a pull request template with a requirements checklist

### ISSUE THREAD

**Issue by PetkovPrime** [Prime-Holding/rx_bloc#585]
As a developer, I would like to have easily accessible information on any development requirements, associated with a certain package. 

A pull request template can be a nice addition to the process, outlining all the tasks that currently need to be performed manually by the developer. It will reduce the chance to forget something important, make it easier to keep track of all new requirements and allow new developers to onboard more easily.

For more information see: [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
Example: [flutter pull request template](https://github.com/flutter/flutter/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1)

Include a template containing the following checklist:

Implementation
- [ ] Implementation matches ticket Acceptance Criteria and Tech Notes

Stability
- [ ] Manually tested against Acceptance Criteria
- [ ] UI checked in Light / Dark mode
- [ ] If other features are affected by the changes verify that they work as expected

Code quality
- [ ] `CHANGELOG.md`, `README.md` and versions in `pubspec.yaml`
- [ ] All packages are updated to the latest supported version
- [ ] Reviewed and cleaned up any unused/commented code from pull request
- [ ] Created draft tickets with any encountered issues not related to the ticket if present.
        - New dependency version with breaking changes
        - Obsolete dependency that needs to be replaced
        - Deprecations
        - General ideas for improvements and refactoring
