### ISSUE TITLE
Implement the offline-first strategy and real-time capability in the Todo App

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#727]
ACs

- [x] Create a REST API for Todo App
- [x] Connect Todo App with the REST API using the retrofit client
- [x] Using the Repository approach create a solution for storing data locally when the device is not connected to the internet
- [x] The same business models should be used for local storage with Realm and API communication  
Note: [Either](https://github.com/realm/realm-dart/issues/683#issuecomment-1659751973) EJSON or JsonSerializable needs to be used for data serialisation
- [x] Real-time (FlexibleSync) communication should be integrated 

![Image](https://github.com/user-attachments/assets/4c261ff7-280f-488c-ba53-1a0906c0fd3f)

**Comment by DDavidPrime** [comment]
While trying to launch the Todo app I got the following error (easily solvable by upgrading the version in Podfile):

```
[!] CocoaPods could not find compatible versions for pod "firebase_core":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`)

Specs satisfying the `firebase_core (from `.symlinks/plugins/firebase_core/ios`)` dependency were found, but they required a higher minimum deployment target.
```

---

The app launches successfully afterwards but on iOS when I press on the FAB an error is logged:

<details>
  <summary>Error message</summary>
  
  ```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: fab
Here is the subtree for one of the offending heroes: Hero
  tag: fab
  dependencies: [_ModalScopeStatus]
  state: _HeroState#7a012
When the exception was thrown, this was the stack: 
#0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:277:11)
#1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:288:8)
#2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:315:13)
#3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321:15)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:321:15)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
// ...
#248    Element.visitChildElements (package:flutter/src/widgets/framework.dart:3835:5)
#249    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:324:13)
#250    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:984:14)
#251    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:939:9)
#252    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#253    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331:11)
#254    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#255    _invoke (dart:ui/hooks.dart:312:13)
#256    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#257    _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```
  
</details>

The same error is not present on Android. Becaues of that, I am not sure whether this needs solving or not.

**Comment by DDavidPrime** [comment]
The iOS build issue is fixed. As for the hero animation log, because it not reliably reproduced, we can leave it be and move forward.

**Comment by StanevPrime** [comment]
@JvnSlv, @DDavidPrime what's the expected action item here ?

**Comment by DDavidPrime** [comment]
There aren't any items left with this one, so unless @JvnSlv says otherwise we can close this ticket.

**Comment by JvnSlv** [comment]
Correct, this can be closed since everything is done
