### ISSUE TITLE
Todo App UX improvements

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#762]
As a user I want the loading states of the application to be presented with a better UX
AC

- [ ]  While the todo is saving on the Add and Edit Todo  Screen
  - [ ] The FAB + button needs to be disabled and in loading state (circular progress indicator inside the button). 
  - [ ] The fields need to be disabled
  - [ ] The X button should be disabled
- [ ]  While the todo is deleting on the Add Details Screen the delete button should be in disabled and loading state
Note: Some of the widget toolkit [buttons](https://pub.dev/documentation/widget_toolkit/latest/widget_toolkit/SmallButton-class.html) can be utilised
-[ ] On Mark All Complete/Incomplete  and Clear Completed action the todo list needs to be in disabled state

**Comment by StanevPrime** [comment]
@DDavidPrime what's the expected action item here ?

**Comment by DDavidPrime** [comment]
@StanevPrime This has been merged to `develop` so we can safely close this ticket.
