### ISSUE TITLE
Add integration tests for Todo app

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#812]
As a developer I want to have the [Todo application](https://github.com/Prime-Holding/rx_bloc/tree/develop/examples/todoapp) contain integration tests that cover common app scenarios using [Patrol](https://leancodepl.docs.page/patrol). See [Familiarization with existing Patrol documentation](https://github.com/Prime-Holding/rx_bloc/blob/develop/packages/rx_bloc_cli/example/docs/patrol_integration_test.md) for more details.

ACs:
- [x] TodoList Page
  - [x] Mark todo complete/incomplete
  - [x] Filters
    - [x] Show All
    - [x] Show Completed
    - [x] Show Incompleted
  - [x] Actions
    - [x] Mark All Complete
    - [x] Mark All Incomplete
    - [x] Clear Completed
- [x] Statistics Page
  - [x] Actions
    - [x] Mark All Complete
    - [x] Mark All Incomplete
    - [x] Clear Completed  
- [x] AddTodo Page
  - [x] Add todo title/description
- [x] EditTodo Page
  - [x] Edit todo title/description
- [x] TodoDetails Page
  - [x] Mark todo complete/incomplete
  - [x] Delete todo

**Comment by DDavidPrime** [comment]
@JvnSlv Add integration test ACs (to cover estimate time)
Estimate: 40h
