### ISSUE TITLE
Checklist of manual steps for feature generation in rx_bloc_cli generated projects

### ISSUE THREAD

**Issue by RomanovaPrime** [Prime-Holding/rx_bloc#858]
As a developer I want to have a checklist of all the manual steps which are needed for feature generation in rx_bloc_cli generated projects in case I don't want to or can't use the relevant Android Studio plugin. 

ACs:
- [x] Document steps required for feature generation
  - [x] Document feature creation and its components
  - [x] Document adding new route(s)
  - [x] Document domain specific dependency injection
