### ISSUE TITLE
Update golden tests with alchemist in Todo app

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#863]
As a developer I want to have a reference of a good implementation of golden tests using the alchemist package. 

ACs:
- [x] Update implementation of helper classes and test configuration
- [x] Update golden tests
- [x] Generate golden tests for the `CI` platform

**Comment by StanevPrime** [comment]
Blocked by [844](https://github.com/Prime-Holding/rx_bloc/issues/844)
